Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -27,14 +27,22 @@ jobs:
     
     - name: Convert and Sync Notebooks
       run: |
-        # Create a list of modified or new .ipynb files
+        set -e  # Exit immediately if a command exits with a non-zero status
+        # Fetch all branches and tags to ensure HEAD~1 is available
+        git fetch --all
+        
+        # Check if HEAD~1 is available
         if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
-          files=$(git diff --name-only HEAD~1 HEAD | grep '^main/.*\.ipynb$')
+          echo "HEAD~1 found"
+          # Create a list of modified or new .ipynb files
+          files=$(git diff --name-only HEAD~1 HEAD | grep '^main/.*\.ipynb$' || true)
         else
+          echo "HEAD~1 not found, handling initial commit or very new branch"
           # Handle initial commit or very new branch
-          files=$(git ls-files --others --exclude-standard --full-name main | grep '\.ipynb$')
+          files=$(git ls-files --others --exclude-standard --full-name main | grep '\.ipynb$' || true)
         fi
 
+        # Process each file
         for file in $files; do
           # Generate the target path in the documentation folder
           target=${file/main/documentation}
